Update panel

diff --git a/panel b/panel
--- a/panel
+++ b/panel
@@ -25,7 +25,7 @@ echo -e "${CYAN}$ascii_art${NC}"
 
 
 
-echo_message "* Installing Dependencies"
+echo "* Installing Dependencies"
 
 sudo apt update
 sudo apt install -y curl software-properties-common
@@ -33,24 +33,24 @@ curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
 sudo apt-get install nodejs -y 
 sudo apt install git -y
 
-echo_message "* Installed Dependencies"
+echo "* Installed Dependencies"
 
-echo_message "* Installing Files"
+echo "* Installing Files"
 
 mkdir -p panel5
-cd panel5 || { echo_message "Failed to change directory to skyport"; exit 1; }
+cd panel5 || { echo "Failed to change directory to skyport"; exit 1; }
 git clone https://github.com/achul123/panel5.git
-cd panel5 || { echo_message "Failed to change directory to panel"; exit 1; }
+cd panel5 || { echo "Failed to change directory to panel"; exit 1; }
 npm install
 
-echo_message "* Installed Files"
+echo "* Installed Files"
 
-echo_message "* Starting Skyport"
+echo "* Starting Skyport"
 
 npm run seed
 npm run createUser
 
-echo_message "* Starting Skyport With PM2"
+echo "* Starting Skyport With PM2"
 
 sudo npm install -g pm2
 pm2 start index.js
